require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsagesController do

  # This should return the minimal set of attributes required to create a valid
  # Usage. As you add validations to Usage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all usages as @usages" do
      usage = Usage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:usages).should eq([usage])
    end
  end

  describe "GET show" do
    it "assigns the requested usage as @usage" do
      usage = Usage.create! valid_attributes
      get :show, {:id => usage.to_param}, valid_session
      assigns(:usage).should eq(usage)
    end
  end

  describe "GET new" do
    it "assigns a new usage as @usage" do
      get :new, {}, valid_session
      assigns(:usage).should be_a_new(Usage)
    end
  end

  describe "GET edit" do
    it "assigns the requested usage as @usage" do
      usage = Usage.create! valid_attributes
      get :edit, {:id => usage.to_param}, valid_session
      assigns(:usage).should eq(usage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Usage" do
        expect {
          post :create, {:usage => valid_attributes}, valid_session
        }.to change(Usage, :count).by(1)
      end

      it "assigns a newly created usage as @usage" do
        post :create, {:usage => valid_attributes}, valid_session
        assigns(:usage).should be_a(Usage)
        assigns(:usage).should be_persisted
      end

      it "redirects to the created usage" do
        post :create, {:usage => valid_attributes}, valid_session
        response.should redirect_to(Usage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved usage as @usage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Usage.any_instance.stub(:save).and_return(false)
        post :create, {:usage => {  }}, valid_session
        assigns(:usage).should be_a_new(Usage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Usage.any_instance.stub(:save).and_return(false)
        post :create, {:usage => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested usage" do
        usage = Usage.create! valid_attributes
        # Assuming there are no other usages in the database, this
        # specifies that the Usage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Usage.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => usage.to_param, :usage => { "these" => "params" }}, valid_session
      end

      it "assigns the requested usage as @usage" do
        usage = Usage.create! valid_attributes
        put :update, {:id => usage.to_param, :usage => valid_attributes}, valid_session
        assigns(:usage).should eq(usage)
      end

      it "redirects to the usage" do
        usage = Usage.create! valid_attributes
        put :update, {:id => usage.to_param, :usage => valid_attributes}, valid_session
        response.should redirect_to(usage)
      end
    end

    describe "with invalid params" do
      it "assigns the usage as @usage" do
        usage = Usage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Usage.any_instance.stub(:save).and_return(false)
        put :update, {:id => usage.to_param, :usage => {  }}, valid_session
        assigns(:usage).should eq(usage)
      end

      it "re-renders the 'edit' template" do
        usage = Usage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Usage.any_instance.stub(:save).and_return(false)
        put :update, {:id => usage.to_param, :usage => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested usage" do
      usage = Usage.create! valid_attributes
      expect {
        delete :destroy, {:id => usage.to_param}, valid_session
      }.to change(Usage, :count).by(-1)
    end

    it "redirects to the usages list" do
      usage = Usage.create! valid_attributes
      delete :destroy, {:id => usage.to_param}, valid_session
      response.should redirect_to(usages_url)
    end
  end

end
